### ISSUE TITLE
Is docker for production working?

### ISSUE THREAD

**Issue by ezorfa** [rrebase/knboard#47]
Hi @rrebase !

I get the following error when i docker compose the docker-compose.yml file:
`Recreating knboard_nginx_1 ... error

ERROR: for knboard_nginx_1  Cannot start service nginx: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/etc/nginx/nginx.conf" to rootfs at "/var/lib/docker/overlay2/e01d2ce743f8f1749800090016be8a53b42aca1eccc2d787f8968fd811bce67e/merged/etc/nginx/nginx.conf" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/etc/nginx/nginx.conf" to rootfs at "/var/lib/docker/overlay2/e01d2ce743f8f1749800090016be8a53b42aca1eccc2d787f8968fd811bce67e/merged/etc/nginx/nginx.conf" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.`

Could you help me with this? Thanks!

**Comment by rrebase** [comment]
Hi @ezorfa. It should still work. 

From your error message it seems that `nginx.conf` is missing, which should be created if you setup the server with the ansible playbook in this repo. This is also covered in the [deployment article](https://www.rrebase.com/posts/deploying-knboard-to-digitalocean-with-ansible).

**Comment by TutoringSprint** [comment]
Hi @rrebase

I was following the instructions on the deployment article but certbot step seems to fail.
```
TASK [certbot : Build containers (may take a few minutes)] *********************
fatal: [XXX.XXX.XX.XX]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"XXX.XXX.XX.XX\". Make sure this host can be reached over ssh: ", "unreachable": true}
PLAY RECAP *********************************************************************
XXX.XXX.XX.XX              : ok=31   changed=24   unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
``` 

I updated the host file according to to the documentation where knboard.com was replaced with the Droplet server ip address (is this correct or should it be the domain) and had also updated knboard:vars to my domain name.

I can confirm that root user is disabled and a new user was created to ssh into the droplet. I had tried to move forward and run the ./init-letsencrypt.sh but can not find it in the root of the repo.

Cheers
