### ISSUE TITLE
One question about types

### ISSUE THREAD

**Issue by sharp** [rrebase/knboard#72]
Hello, I check the code in types.ts:
```
export interface IColumn 
export interface ITask 
export interface Board
export interface User 
```
why some start with `I` , some are not ?

**Comment by rrebase** [comment]
👋 Hey! There's no good reason for this and they should actually be consistent. Could add a lint rule to avoid this :)

**Comment by rrebase** [comment]
👋 Hey! There's no good reason for this and would rather drop the `I` prefix. It might have been historically there to avoid naming conflicts when importing a that file includes a Type and React component with the same name. Using `import type` would resolve that now.
